server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wws_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: //记得写密码！记得写密码！记得写密码！自己的数据库密码！-数据库无法启动就用管理员启动、任务管理器强制启动、csdn，然后要带双引号
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

python:
  api:
    url: http://localhost:8000
